// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7q4L__gYlJOntnhRsJ1clApb0LxNHg94',
    appId: '1:1001958185957:web:7dd9b47b37ab345b662d0c',
    messagingSenderId: '1001958185957',
    projectId: 'fitfusion-backend-52ef5',
    authDomain: 'fitfusion-backend-52ef5.firebaseapp.com',
    databaseURL: 'https://fitfusion-backend-52ef5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitfusion-backend-52ef5.firebasestorage.app',
    measurementId: 'G-M5CVJ6NDWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJBElIVA0rfoFNQwPbcmzgYB3Yka8NICk',
    appId: '1:1001958185957:android:b2dd1ed3805deea6662d0c',
    messagingSenderId: '1001958185957',
    projectId: 'fitfusion-backend-52ef5',
    databaseURL: 'https://fitfusion-backend-52ef5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitfusion-backend-52ef5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7q4L__gYlJOntnhRsJ1clApb0LxNHg94',
    appId: '1:1001958185957:web:78569641dcf53086662d0c',
    messagingSenderId: '1001958185957',
    projectId: 'fitfusion-backend-52ef5',
    authDomain: 'fitfusion-backend-52ef5.firebaseapp.com',
    databaseURL: 'https://fitfusion-backend-52ef5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitfusion-backend-52ef5.firebasestorage.app',
    measurementId: 'G-JTW4WS4ZLL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGycUPg91uiImJNp3v1Aof6rIufazFABU',
    appId: '1:1001958185957:ios:f33c8c98907fb02a662d0c',
    messagingSenderId: '1001958185957',
    projectId: 'fitfusion-backend-52ef5',
    databaseURL: 'https://fitfusion-backend-52ef5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitfusion-backend-52ef5.firebasestorage.app',
    iosClientId: '1001958185957-nuc790me9kfs6rooenmoqn70smi2prd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitfusion',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGycUPg91uiImJNp3v1Aof6rIufazFABU',
    appId: '1:1001958185957:ios:f33c8c98907fb02a662d0c',
    messagingSenderId: '1001958185957',
    projectId: 'fitfusion-backend-52ef5',
    databaseURL: 'https://fitfusion-backend-52ef5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitfusion-backend-52ef5.firebasestorage.app',
    iosClientId: '1001958185957-nuc790me9kfs6rooenmoqn70smi2prd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitfusion',
  );

}